version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies"
      - make install
  pre_build:
    commands:
      - echo "Linting code"
      - make lint
  build:
    commands:
      - echo "Running tests"
      - make test
  post_build:
    commands:
      - echo "Build finished"

artifacts:
  files:
    - '**/*'
  discard-paths: no